### ISSUE TITLE
The latest v0.0.0.73 version slows down editing in Visual Studio

### ISSUE THREAD

**Issue by Diesel1017** [ycherkes/ObjectDumper#46]
Hi,

The released last version really slows down text editing, renaming and all refactoring operations.

Object Dumper version: 0.0.0.73
Microsoft Visual Studio Community 2022 v17.4.4
The solution has 50+ projects with .net4.7.2 framework.
I use several extensions, the moment I turn disable the ObjectDumper, visual studio becomes usable again.

Unfortunately I cannot provide much more information.
Please look into what the problem might be.

**Comment by ycherkes** [comment]
Hi,
That's weird because ObjectDumper doesn't perform any tracking operations, just 5 menus + commands that are reading the text from the current code editor when you're running the command.
Have you got a Visual Studio "the extension is slowing down..." report?
Did it happen after you run the "Dump as" command or no?
I will try to reproduce the issue, but if you have any additional information that can help me  - please let me know.
Can you please enable the extension again and check if the issue is reproducing again?

**Comment by ycherkes** [comment]
You can also start a VS with `devenv /log` and then look at "%AppData%\Microsoft\VisualStudio\17.0_64bc002a\ActivityLog.xml" if there are any performance anomalities: [Measuring impact of auto loaded extensions using Activity log](https://learn.microsoft.com/en-us/visualstudio/extensibility/how-to-diagnose-extension-performance?view=vs-2022#measuring-impact-of-auto-loaded-extensions-using-activity-log)

For example JetBrains ReSharper slows down my VS Community 2022 v17.4.4:
```
<entry>
    <record>2100</record>
    <time>2023/02/09 13:32:42.716</time>
    <type>Information</type>
    <source>UIDelayNotifications</source>
    <description>A UI delay (Delay ID = 5) has been detected. (Session ID=a931eaa8-4664-4794-ad11-b11b0aad3fec; Blamed extension=&quot;JetBrains ReSharper 2022.2.4&quot;; Notification shown? Yes.)</description>
</entry>
```

**Comment by ycherkes** [comment]
Hi @Diesel1017 
I wasn't able to reproduce the issue you mentioned, but I fixed all suspicious code. Could you try the latest version 0.0.0.75 and let me know if the issue still exists?

**Comment by ycherkes** [comment]
Closing due to reporter's inactivity.
