### ISSUE TITLE
Question regarding properties with no setter

### ISSUE THREAD

**Issue by mwestley61** [ycherkes/ObjectDumper#61]
Hi,
I used ObjectDumper (_which I am finding very useful_) to intercept and generate a variable for an [HttpWebResponse ](https://learn.microsoft.com/en-us/dotnet/api/system.net.httpwebresponse?view=net-7.0) object. (_see screenshot_)  Upon copying it into an actual test program I'm getting numerous messages (red squiggly lines) from the Visual Studio editor on many of the properties.  Since this Microsoft object seems to have read only (getter only) properties I wonder is it appropriate that ObjectDumper generates an assignment statement for those that have no setter?  Do you have any thought or ideas about this and possible suggestions of things I might try to get around this? 
![image](https://github.com/ycherkes/ObjectDumper/assets/108296376/8ba4bd37-b53e-43ed-ae73-80c44cc2f4fd)

**Comment by ycherkes** [comment]
Hi @mwestley61,
Usually Object Dumper generates an assignment statements for writeable properties only. 
Seems you modified this setting.
Please revert it back as shown on a screenshot to get the desired behavior.
![image](https://github.com/ycherkes/ObjectDumper/assets/13467759/3ba20e21-eaa6-4b98-a0ac-baf14f707456)

**Comment by ycherkes** [comment]
I thought about the HttpWebResponse & HttpWebRequest special serialization but have not found a way how to implement it.

The only thing that can be helpful at the moment it's a dumping of inner content of HttpWebResponse and use it for mocking purposes:

0. Assuming the HttpWebResponse variable has the name **response**.
1. Paste the code below to the **Immediate Window**, select this code, run the "Dump as C#" command (or just press Enter instead - but in this case the printed result can be trimmed (Length <= 65535 chars))

`Convert.ToBase64String(((System.Net.HttpWebResponse)response)._httpResponseMessage.Content.ReadAsByteArrayAsync().ConfigureAwait(false).GetAwaiter().GetResult())`

2. Copy the dumped string value and add the following code for mocking:

```
var stringValue = "<BASE64 Encoded Data>";
var bytes = Convert.FromBase64String(stringValue);
using var responseStream = new MemoryStream(bytes);
var mockedResponse = new Mock<HttpWebResponse>();
mockedResponse.Setup(c => c.GetResponseStream()).Returns(responseStream);
```

https://stackoverflow.com/questions/9823039/is-it-possible-to-mock-out-a-net-httpwebresponse

Instead of dumping to Base64 string you can write the response content directly to file and read from the file correspondingly without Object Dumper:

1. Run in the Immediate Window:

`System.IO.File.WriteAllBytes("C:\\Temp\\testFile.pdf", ((System.Net.HttpWebResponse)response)._httpResponseMessage.Content.ReadAsByteArrayAsync().ConfigureAwait(false).GetAwaiter().GetResult());`

2. Then use this file in tests:

```
using var responseStream = new FileStream("C:\\Temp\\testFile.pdf", FileMode.Open, FileAccess.Read);
var mockedResponse = new Mock<HttpWebResponse>();
mockedResponse.Setup(c => c.GetResponseStream()).Returns(responseStream);
```

**Comment by mwestley61** [comment]
Yes, this is exactly the path I was heading down.  I definitely was looking into the post on StackOverflow site you referred to.  Thanks also for the little extra help with the code you provided here to be that I'll likely use in what I'm trying to accomplish.  I believe it should help.  Thanks again for supporting your project so responsively!  👍 (P.S. - I see now that I should get a little more familiar with all the settings you've provided on ObjectDumper! 🥇)
